<a href="https://colab.research.google.com/github/blackartus/DataScienceBootCamp/blob/main/01/wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
>Strona Biblioteki: [https://numpy.org/](https://numpy.org/)

>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)

>Podstawowa biblioteka do obliczeń numerycznych w języku Python.

>Aby zainstalować bibliotekę NumPy, użyj polecenia:

```
>>> pip install numpy
```


# Spis Treści
1. [Podstawy](#a1)
2. [Typy Danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Algebra liniowa](#a10)

#Podstawy

In [1]:
import numpy as np
np.__version__

'1.22.4'

###1D Array

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
type(x) # zwróci typ obiektu

numpy.ndarray

In [4]:
x.shape # zwróci kształt tablicy. Tutaj 1 wiersz z trzema kolumnami

(3,)

In [5]:
x.dtype # zwróci typ danych w tablicy

dtype('int64')

In [6]:
x.ndim # zwraca ilość wymiarów naszej tablicy


1

###2D Array

In [7]:
y = np.array([
    [2, 4, 6],
    [6, 7, 8]
])
print(y)

[[2 4 6]
 [6 7 8]]


In [8]:
y.ndim

2

In [9]:
y.shape


(2, 3)

In [10]:
y2 = np.array([
    [2,3,4,5,6],
    [3,4,5,3,43],
    [4,5,6,65,44],
    [54,55,67,89,98]
])
y2.shape

(4, 5)

###3D Array

In [11]:
x3 = np.array(  # Tablica 3D - tutaj 2 tablice, 3 wiersze, 4 kolumny
    [
        [[4,3,2, 5], 
         [33, 8, 2, 5],
         [32,55,12, 5]],
        
        [[32,33,76,3], 
         [43,4,67, 3],
         [32,54,23, 3]]
    ]
)
x3.ndim

3

In [12]:
x3.shape

(2, 3, 4)

###Typy Danych

In [13]:
A = np.array([1.2,3.3], dtype='int')
A.dtype

dtype('int64')

In [14]:
print(A)

[1 3]


In [15]:
A=np.array([1,3,5], dtype='float')
A

array([1., 3., 5.])

In [16]:
A.dtype

dtype('float64')

In [17]:
print(A)

[1. 3. 5.]


In [18]:
A=np.array([True, False])
A.dtype

dtype('bool')

###Tworzenie Tablic

In [19]:
# Tworzymy tablicę dowolnego rozmiaru wypełnioną zerami
A = np.zeros(shape=(3,3,5))
print(A)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [20]:
# Tworzymy tablicę dowolnego rozmiaru wypełnioną jedynkami
A = np.ones(shape=(5,5), dtype=int)
B = np.ones(shape=(4,4,4))
A, B

(array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [21]:
A = np.ones(shape=(5,5), dtype='int')
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# Tworzymy tablicę o dowolnym rozmiarze i wypełnioną dowolną wartością
A = np.full(shape=(3,3), fill_value=5, dtype='int')
A

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [23]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
A = np.arange(start=5, stop=10)
A

array([5, 6, 7, 8, 9])

In [25]:
A = np.arange(start=5, stop=100, step=5)
A

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [26]:
A = np.arange(start=500, stop=100, step=-50)
A

array([500, 450, 400, 350, 300, 250, 200, 150])

In [27]:
A = np.arange(start=0, stop=1, step=0.05)
A

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [28]:
# Tworzymy tablicę, gdzie podajemy start i stop oraz ilość elementów pomiędzy, które będą równo rozłożone
A = np.linspace(start=0, stop=1, num=12)
A 

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [29]:
# Zmieniamy kształt tablicy
A = np.arange(10)

In [30]:
B= A.reshape((-1,5))
B

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
A = np.arange(300)

In [32]:
A.reshape((-1,12))

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167],
       [168, 169, 170, 171, 172, 1

In [33]:
A.reshape((15, -1))

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

In [34]:
A.shape

(300,)

In [35]:
A.ndim


1

In [36]:
B= A.reshape((15, -1))
B.ndim

2

In [37]:
B.shape

(15, 20)


###Podstawowe Operacje na tablicach

In [38]:
A = np.array([2,4,1,3])
B = np.array([3,1,-1,2])
print(A)
print(B)

[2 4 1 3]
[ 3  1 -1  2]


In [39]:
A+B

array([5, 5, 0, 5])

In [40]:
A-B

array([-1,  3,  2,  1])

In [41]:
A*B

array([ 6,  4, -1,  6])

In [42]:
A/B

array([ 0.66666667,  4.        , -1.        ,  1.5       ])

In [43]:
A+3

array([5, 7, 4, 6])

In [44]:
A*3

array([ 6, 12,  3,  9])

In [45]:
3*A

array([ 6, 12,  3,  9])

In [46]:
15-A

array([13, 11, 14, 12])

In [47]:
A+B

array([5, 5, 0, 5])

In [48]:
np.add(A,B)

array([5, 5, 0, 5])

In [49]:
#Mnożenie Macieży
X= np.array([[1,3], [-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [50]:
X*Y

array([[6, 0],
       [2, 0]])

In [51]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [52]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [53]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [54]:
X @ Y

array([[  3,   6],
       [-12,   0]])

###Generowanie Liczb Pseudolosowych 

In [55]:
np.random.seed(0)

In [56]:
np.random.randn()

1.764052345967664

In [57]:
np.random.seed(0)

In [58]:
np.random.randn()

1.764052345967664

In [59]:
np.random.randn()

0.4001572083672233

In [60]:
np.random.randn(10) 

array([ 0.97873798,  2.2408932 ,  1.86755799, -0.97727788,  0.95008842,
       -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,  1.45427351])

In [61]:
np.random.randn(10, 4) # 10 oznacza liczbę wierszy (utożsamiamy z liczbą próbek) 4 oznacza liczbę kolumn (utożsamiany z liczbą zmiennych)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [62]:
np.random.rand()

0.1965823616800535

In [63]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [64]:
np.random.rand(10,4)

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [65]:
# Generujemy liczbę całkowitą 0-9
np.random.randint(10)

8

In [66]:
# generujemy liczbę dwucyfrową od 10 do 99
np.random.randint(low=10, high=100)

26

In [67]:
# Generujemy Tablicę z dziesięcioma elementami z przedziału 10 do 99
np.random.randint(low=10, high=100, size=10)

array([34, 39, 31, 35, 90, 70, 71, 93, 43, 42])

In [68]:
# wybieramy jeden element z listy
np.random.choice([3,4,2,5,2])

2

In [69]:
# wybieramy jeden element z listy
np.random.choice(['python', 'java','javascript'])

'java'

In [70]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
# tasujemy listę data. To działanie zmienia oryginalną listę
np.random.shuffle(data)
data

array([2, 4, 1, 3, 9, 0, 8, 7, 5, 6])

###Podstawowe Funkcje

In [72]:
a = np.exp(1)
print(a)
# exp(1) -> zwróci stałą Eulera (2.718281828459045)

2.718281828459045


In [73]:
a = np.array([[1,2,3,4],[3,4,5,6]])

In [74]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692,  54.59815003],
       [ 20.08553692,  54.59815003, 148.4131591 , 403.42879349]])

In [75]:
# Pierwiastek kwadratowy
np.sqrt(2)


1.4142135623730951

In [76]:
np.sqrt(3)

1.7320508075688772

In [77]:
np.sqrt(9)

3.0

In [78]:
# Zwraca True jeśli wszystkie elementy są True. Jeśli choć jeden element jest False, zwróci False
np.all([8, 6, 1, 1, 9, 2, 3, 7, 5, 4])

True

In [79]:
# Zwraca True jeśli choć jeden element zwróci True. False jeśli wszystkie zwracają False
np.any([1,3,4,0,0,0])

True

In [80]:
np.any([0,0,0,0])

False

In [81]:
np.any([0,0,0,1])

True

In [82]:
A = np.random.rand(5)
A

array([0.87845219, 0.10286336, 0.09237389, 0.35404666, 0.55181626])

In [83]:
A[np.argmax(A)]

0.878452190276042

In [84]:
A[np.argmin(A)]

0.0923738894608982

In [85]:
np.argsort(A)

array([2, 1, 3, 4, 0])



```
# Sformatowano jako kod
```

###Indeksowanie, Wycinanie

In [86]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
# A[index], A[start:stop:step], A[:stop], A[start:]

In [88]:
A[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
B = A[-1:0:-2]
B

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [90]:
# Wycinamy konkretne indexy podając listę indeksów
A[[2,5,7]]

array([2, 5, 7])

In [91]:
A[3:7]

array([3, 4, 5, 6])

In [92]:
  A = A.reshape(4,5)
  A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [93]:
# Jeśli chcemy zwrócić wiersz
# A[Index Wiersza]
A[0]

array([0, 1, 2, 3, 4])

In [94]:
# Jeśli chcemy zwócić kolumnę
# A[:, index kolumny]
A[:,0]

array([ 0,  5, 10, 15])

In [95]:
# Jeśli chcemy wyciąć ostatnią kolumnę możemy użyć -1
A[:,-1]

array([ 4,  9, 14, 19])

In [96]:
# Możemy oczywiście wyciąć konkretny element => np. 6 drugi wiersz i druga kolumna
A[1,1]

6

In [97]:
# Jeśli chcemy wyciąć fragment podajemy zakresy
A[1:2, 1:4]

array([[6, 7, 8]])

In [98]:
# Możemy też prtzypisywać wartości
A[1,2] = 29
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 29,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

###Interacja po Tablicach

In [99]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 29,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [101]:
for i in A:
  print(f'Wiersz: {i}')

Wiersz: [0 1 2 3 4]
Wiersz: [ 5  6 29  8  9]
Wiersz: [10 11 12 13 14]
Wiersz: [15 16 17 18 19]


In [102]:
for row in A:
  print(row[1])

1
6
11
16


In [103]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 29]
[10 11 12]
[15 16 17]


In [104]:
# używając atrybutu ".flat" spłaszczamy tablicę dzięki czemu możemy iterować po każdym elemencie
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
29
8
9
10
11
12
13
14
15
16
17
18
19


###Zmiana rozmiaru tablic

In [105]:
# Zwraca kształt tablicy.
A.shape

(4, 5)

In [106]:
# Jak wcześniej. Zmiana kształtu tablicy.
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 29],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [110]:
A.flat

In [108]:
# Wypłaszczenie tablicy do jednego wymiaru.
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 29,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [111]:
# Trablica została przetransponowana. Wiersze stały się kolumnami, a kolumny wierszami.
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 29, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

###Maski Logiczne

In [114]:
A = np.arange(start=-10, stop=10, step=0.5)
A.shape

(40,)

In [118]:
A = A.reshape(10,-1)

In [119]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [120]:
# Możemy powyższy sposób wykorzystać do odsiania wartości mniejszych od zera
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [125]:
# Jeśli chcemy podać przedział, czyli podajemy dwa warunki używamy np.bitwise_and()
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [122]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [123]:
# Mamy też do dyspozycji alternatywę: np.bitwise_or()
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

###Broadcasting